## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
notifications:
  email: true
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
jobs:
  include:
    - stage: "Tests"
      os: linux
      julia: 1.1
    - # continue
      os: osx
      julia: 1.1
    - # continue
      os: linux
      julia: 1.0
    - stage: Semantic Release
      if: branch = master AND type != pull_request
      language: python
      os: linux
      python: 3.6
      install:
        - pip install typing
        - pip install python-semantic-release
      script:
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - semantic-release publish
      after_success: skip